### ISSUE TITLE
API 2.8: 400 Client Error Bad Request for url

### ISSUE THREAD

**Issue by tableaukun** [bryantbhowell/tableau_tools#39] opened 2018-09-10 22:28 UTC
tableau_tools Version = 4.5.3
Python Version = 2.7.10
OS Version = macOS High Sierra 10.13.3
Tableau Server Version = 10.5

Hi,

I'm getting an error refreshing an extract using the API 2.8 call for _update_datasource_now_. I get the following:
`HTTPError: 400 Client Error: Bad Request for url: https://server/api/2.8/sites/{site_id}/datasources/{ds_id}/refresh`

I am able to manually refresh data sources directly on Tableau Server. Do I need specific permissions to do the same via code? Currently, my site role is Publisher.

Thanks

**Comment by tableaukun** [comment] 2018-09-11 21:55
It looks like you cannot publish a datasource AND refresh it in the same Sign In session. You have to Sign Out (t.signout) and sign back in again for it to work.

**Comment by bryanthowell-tableau** [comment] 2018-09-14 19:34
Have you tried putting a sleep in (time.sleep(3) for example) before triggering the refresh? Sometimes if you do a statement immediately after creation the internal SOLR indexes haven't updated yet so requests on the new objects fail

**Comment by tableaukun** [comment] 2018-09-14 22:34
I was running individual cells in Jupyter, so as I was testing, I waited more than 3 seconds between calls.

I will mention that the data source (same name/project) already existed in my example. Overwriting does not change the datasource_luid, so it stays the same. No matter how many times I try to refresh the datasource in the same session, it would not work. I had to sign out and sign back in for it to work.

**Comment by bryanthowell-tableau** [comment] 2018-09-17 11:59
One of the other issues that was reported recently found that the Publish calls were leaving the connection in a slightly wrong state, which may be the cause of this. I've put in a change which I think will fix this that will be in the upcoming 4.6.0 release. I'll let you know as soon as I get that release up and finished.

**Comment by bryanthowell-tableau** [comment] 2018-09-17 19:22
I've just uploaded v.4.6.0 to PyPi, can you upgrade via pip and let me know if the issue is resolved?

**Comment by tableaukun** [comment] 2018-09-17 19:48
Looks like that resolved the issue. Thanks!

**Closed as completed** 2018-09-17 19:52 UTC
